version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    build:
      context: .
      dockerfile: docker/mysql-dockerfile/Dockerfile
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'beagle_database'
      MYSQL_USER: 'luni'
      MYSQL_PASSWORD: 'dalu'
      MYSQL_ROOT_PASSWORD: 'dalu'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    environment:
        APP_ENV: dev
    ports:
      - 9000:80
    networks:
      - laravel
    user: ${USER_ID}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PMADB: phpmyadmin
      PMA_USER: root
      PMA_PASSWORD: dalu
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    networks:
      - laravel


networks:
  laravel:

